---
title: Lateef Ahmad Wani
timezone: Asia/Kolkata
collections:
  posts:
    title: Posts
    output: true
  publications:
    title: Publications
    output: true
    permalink: "/:collection/:path/"
  research:
    title: Research
    output: true
    permalink: "/:collection/:path/"
  talks:
    title: Talks
    output: true
    permalink: "/:collection/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true
- scope:
    path: ''
    type: pages
  values:
    layout: single
    author_profile: true
- scope:
    path: ''
    type: teaching
  values:
    layout: single
    author_profile: true
    share: false
    comments: true
- scope:
    path: ''
    type: publications
  values:
    layout: single
    author_profile: true
    share: true
    comments: true
- scope:
    path: ''
    type: research
  values:
    layout: single
    author_profile: true
    share: true
    comment: true
- scope:
    path: ''
    type: talks
  values:
    layout: talk
    author_profile: true
    share: true
locale: en-US
title_separator: "-"
name: Lateef Ahmad Wani
description: PhD in Mathematics
url: https://lateefwani.github.io/
baseurl: 
repository: lateefwani/lateefwani.github.io
teaser: 
breadcrumbs: false
words_per_minute: 160
future: false
read_more: disabled
talkmap_link: false
comments:
  provider: 
  disqus:
    shortname: 
  discourse:
    server: 
  facebook:
    appid: 
    num_posts: 
    colorscheme: 
staticman:
  allowedFields:
  - name
  - email
  - url
  - message
  branch: gh-pages
  commitMessage: New comment.
  filename: comment-{@timestamp}
  format: yml
  moderation: true
  path: _data/comments/{options.slug}
  requiredFields:
  - name
  - email
  - message
  transforms:
    email: md5
  generatedFields:
    date:
      type: date
      options:
        format: iso8601
atom_feed:
  path: 
google_site_verification: 
bing_site_verification: 
alexa_site_verification: 
yandex_site_verification: 
twitter:
  username:
facebook:
  username: 
  app_id: 
  publisher: 
og_image: profile.png
social:
  type: 
  name: 
  links: 
analytics:
  provider: false
  google:
    tracking_id: 
author:
  name: Lateef Ahmad Wani
  avatar: myself.jpeg
  bio: NBHM Postdoc Fellow
  location: Roorkee, IN
  employer: 
  pubmed: 
  orcid: https://orcid.org/0000-0003-3326-7652
  googlescholar: https://scholar.google.com/citations?user=f-GZ_FcAAAAJ&hl=en&oi=ao
  email: nali@ph.iitr.ac.in
  researchgate: 
  uri: 
  bitbucket: 
  codepen: 
  dribbble: 
  flickr: 
  facebook: 
  foursquare: 
  github: lateefwani
  gitlab: lateefwani
  google_plus: 
  keybase: 
  instagram: 
  impactstory: 
  lastfm: 
  linkedin: 
  pinterest: 
  soundcloud: 
  stackoverflow: 
  steam: 
  tumblr: 
  twitter: 
  vine: 
  weibo: 
  xing: 
  youtube: 
  wikipedia: 
include:
- ".htaccess"
- _pages
- files
exclude:
- "*.sublime-project"
- "*.sublime-workspace"
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- CHANGELOG
- Capfile
- Gemfile
- Gruntfile.js
- LICENSE
- README
- Rakefile
- assets/js/_main.js
- assets/js/plugins
- assets/js/vendor
- config
- gulpfile.js
- log
- node_modules
- package.json
- tmp
- vendor
keep_files:
- ".git"
- ".svn"
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title/"
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jekyll-redirect-from
whitelist:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
compress_html:
  clippings: all
  ignore:
    envs: development
